case erlang:function_exported(rebar3, main, 1) of
    true -> % rebar3
        CONFIG;
    false -> % rebar 2.x or older
        %% Rebuild deps, possibly including those that have been moved to
        %% profiles
        Deps = proplists:get_value(deps, CONFIG),
        MapFun = fun({Name, Repo}) ->
            {Name, ".*", Repo}
            end,
        Deps1 = lists:map(MapFun, Deps),
        [{deps, Deps1} | lists:keydelete(deps, 1, CONFIG)]
end.
